### ISSUE TITLE
some issuses about stable-diffusion-2-1-base

### ISSUE THREAD

**Issue by 12shuai** [yuval-alaluf/Attend-and-Excite#35]
for some prompts I test, the method appear bad performance, i don't know why

**Comment by hila-chefer** [comment]
Thanks for your interest @12shuai!
I’m not sure which prompts you are referring to, since no specific prompts were mentioned in the issue, but I can think of several possible explanations:

1. As mentioned in our limitations section, our method relies on the pre-trained model without fine-tuning it, and therefore is limited by its expressive power. If your prompt resides outside of the SD distribution, our method can lead to OOD latents (especially if the iterative refinement was invoked repeatedly).
2. Subjects with multiple tokens- if your subject is split to multiple tokens, you may have chosen the least dominant sub word, again leading to the same issue as point 1 (see [this issue](https://github.com/yuval-alaluf/Attend-and-Excite/issues/32) for more details).
3. Subjects that are not nouns- if you choose to strengthen other parts of speech, our method attempts to drive the token’s attention score to 1 which is not a natural value for other parts of speech, and you may need to adjust the attention threshold you require.

I hope this helps.
