### ISSUE TITLE
Intuition behind choosing step size

### ISSUE THREAD

**Issue by nttung1110** [yuval-alaluf/Attend-and-Excite#39]
Hi,

First of all, thanks for your excellent research work. This is pretty innovative and motivated me to conduct further experiment on your codebase. I would love to ask about choosing a practical step size when updating latent. How did you come up with your strategy of choosing step size, i.e, linear spacing which decrease from 1 to 0.5? What would be a practical step size do you think if we have an additional loss attached with the existing attend-and-excite loss? 

I tried to add an additional loss to mimic the behavior of my expected generation result but it seems like it does not converge very well. It would be great if we could discuss further on this. Many thanks for spending your time and effort.

Best.

**Comment by hila-chefer** [comment]
Hi @nttung1110, thanks for your interest!

The intuition behind this choice is that, as mentioned in the paper, most of the spatial information (e.g., location of objects) is determined in the first denoising steps, while the last ones mainly influence fine details. Since our goal is to encourage the generation of neglected subjects, we perform larger step sizes in the first denoising steps.
You can also see the impact of applying our method in the last timesteps in Fig. 12 of the paper. The figure demonstrates that these steps mostly add artifacts and do not induce meaningful changes in the resulting image.
 
Referring to your specific issue- I do not recall a convergence issue with our method. The main issue that I saw before adapting the step size was that the loss decreased very significantly but resulted in OOD latents and OOD images. 
Without further details on the objective you are exploring it's hard to come up with an explanation to why this is happening in your case.
I would start with very large step sizes just to make sure that your loss can decrease (without our method).

I hope this helps!

**Comment by nttung1110** [comment]
Hi,

Thanks for your detailed explanation. I would try to explore more to fix this issue.
