### ISSUE TITLE
Latent not updated on first iteration of iterative refinement

### ISSUE THREAD

**Issue by UnrealLink** [yuval-alaluf/Attend-and-Excite#40]
Hi,

Very interesting work!
While going through the codebase, I noticed that when performing iterative refinement, the latents are passed twice through the unet without an update in between. Is this the expected behavior?

Also this is nitpicking but I believe in the paper you stated "We set the iterations to 𝑡1 = 0, 𝑡2 = 10, and 𝑡3 = 20", but I believe this should be 𝑡1 = 50, 𝑡2 = 40, and 𝑡3 = 30 if we follow the notations of the rest of the paper?

Best,

**Comment by hila-chefer** [comment]
Hi @UnrealLink, thanks for your interest!

Can you please reference the specific line in the code you are referring to? Couldn't locate this behavior in our [iterative refinement code](https://github.com/yuval-alaluf/Attend-and-Excite/blob/main/pipeline_attend_and_excite.py#L285).

Regarding the second question- technically, if using the notations from the preliminaries section of the paper, the timesteps should be t_T, t_{T-10}, t_{T-20}. The intention in our notations was to refer to the first *denoising step* as t0 (as also stated in the text). I agree that there is some abusing of notations there, but I hope it's clear since the text explicitly mentioned these steps as the denoising steps, and not the diffusion timesteps.

I hope this helps!

**Comment by UnrealLink** [comment]
Hi @hila-chefer,

Thank you for your answer and sorry for the late reply!

About the iterative refinement code, I worded my comment poorly, I meant that I believe that steps 1 through 8 of [Agorithm 1](https://arxiv.org/pdf/2301.13826.pdf#page=4) in the paper are done twice with the same input in the code:
 - you do a pass through the U-Net and compute the loss to know if you need to perform iterative refinement [here](https://github.com/yuval-alaluf/Attend-and-Excite/blob/main/pipeline_attend_and_excite.py#L515-L531)
 - and on your first pass of the iterative refinement your recompute these quantities with the same input [here](https://github.com/yuval-alaluf/Attend-and-Excite/blob/main/pipeline_attend_and_excite.py#L289-L303)

Am I missing something?
In any case it wouldn't affect the results but it might save a bit of compute!

About the second question, thank you I had missed the denoising/diffusion timesteps distinction!

Best,

**Comment by hila-chefer** [comment]
Hi @UnrealLink, thanks for the clarification!
You are indeed right that the same code will be performed twice in a row if we do iterative refinement, I think there’s a trade off here between code duplication and simplicity, and the overhead from running that logic once too many for each iterative refinement application.
In any case, as you mentioned, this does not impact the result :)

I hope this answers your questions :)

**Comment by UnrealLink** [comment]
Hi @hila-chefer, thanks again for your answer!
