### ISSUE TITLE
KeyError: 'up_cross'  

### ISSUE THREAD

**Issue by wangzhen-ing** [yuval-alaluf/Attend-and-Excite#41]
hello, thanks for your work.

recently, I ran this attend and excite code and This bug occurs, I don't know how to solve this. 
`"self.attention_store = {}"`

I read the issues of prompt-to-prompt, and they say this issue is related to the version of diffusers. need to revise the code of `register_attention_control` to adapt to the new version of diffusers. but in your code, you have revised the code of `register_attention_control` and `AttendExciteCrossAttnProcessor`, so I don't know how to solve this problem

I am looking forward to your answer very much！

**Comment by hila-chefer** [comment]
Hi @wangzhen-ing, thanks for your interest!

I haven't seen this issue before it sounds like a package version issue, but since the Attend-and-Excite is also supported in the [official diffusers library](https://huggingface.co/docs/diffusers/api/pipelines/attend_and_excite) you can always try running it from diffusers with their latest version and see if that helps solve the issue.

I hope this helps!

**Comment by wangzhen-ing** [comment]
> Hi @wangzhen-ing, thanks for your interest!
> 
> I haven't seen this issue before it sounds like a package version issue, but since the Attend-and-Excite is also supported in the [official diffusers library](https://huggingface.co/docs/diffusers/api/pipelines/attend_and_excite) you can always try running it from diffusers with their latest version and see if that helps solve the issue.
> 
> I hope this helps!

Thank you very much for your reply
